language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"  
  - "nightly"  # nightly build

install:
  - pip install .
  
# command to run tests
script:
  - cd tests
  - python ./test-fluoly.py
